# After changing this file, check it on:
#   http://lint.travis-ci.org/

os:         linux
language:   python

matrix:
  fast_finish: true
  allow_failures:
    - os: windows

  include:
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      env:
        - PYTHON_EXE=python3
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
        #- ONNX_DETECTION=on # temporarily switched off to save time
      before_install:
        - choco install python --version 3.8.0
        - cmd <<< "mklink C:\\Python38\\python3.exe C:\\Python38\\python.exe"
        - choco install gzip
        - python -m pip install --upgrade pip
        - ln -s /c/Windows/System32/tar.exe /c/Python38

    - language: python
      python: 3.8
      env:
        - PYTHON_EXE=python

    - language: python
      python: 3.9
      env:
        - ONNX_DETECTION=on
        - PYTHON_EXE=python

    - language: python
      python: 3.6
      env:
        - ONNX_DETECTION=on
        - PYTHON_EXE=python

    - language: python
      python: 3.7
      env:
        - PYTHON_EXE=python
      before-install:
        - ${PYTHON_EXE} -m pip install --ignore-installed --verbose pip setuptools importlib-metadata

    - os: osx
      osx_image: xcode11.2  # Python 3.7, but may change with time
      language: shell       # 'language: python' is an error on Travis CI macOS
      env:
        #- ONNX_DETECTION=on # temporarily switched off to save time
        - PYTHON_EXE=python3

install:
    - CWD=`pwd`
    - PATH=$PATH:$CWD:$CWD/axs
    - THIS_REPO_NAME=`basename $CWD`
    - echo "TRAVIS_OS_NAME=${TRAVIS_OS_NAME}, TRAVIS_PYTHON_VERSION=${TRAVIS_PYTHON_VERSION}"
    - echo "CWD=${CWD}, THIS_REPO_NAME=${THIS_REPO_NAME}, PATH=${PATH}"
    - which ${PYTHON_EXE}
    - ${PYTHON_EXE} --version
    - which git
    - git --version
    - git clone https://github.com/krai/axs.git
    - axs version
    - axs byquery git_repo,collection,repo_name=$THIS_REPO_NAME
    - wget https://raw.github.com/lehmannro/assert.sh/master/assert.sh

script:
    - axs byname loadgen_example , run
    - bash test_axs2mlperf.sh
