name: Docker Image CI

on:
  push:
    branches: [ "test" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Update the Docker image
      run: cd demo && docker build --build-arg="BRANCH=master" --build-arg="CLEAN=false" -t axs:benchmarks.test -f Dockerfile .

    - name: Run Test
      run: cd demo && ./run_test.sh
