name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Update the Docker image
      run: cd demo && docker build --no-cache --build-arg="BRANCH=master" --build-arg="CLEAN=false" -t axs:benchmarks.test -f Dockerfile .

    - name: Run Test
      run: cd demo && ./run_test.sh

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        branch: stable
